-- Sanity check: how many rows do we have?
SELECT COUNT(*) AS total_rows
FROM sales;

-- Optional: quick preview
SELECT *
FROM sales
LIMIT 5;

-- KPI BLOCK 1: OVERALL BUSINESS VOLUME
-- Objective: quantify the scale of activity in the dataset:
--   - total_revenue        → overall sales generated
--   - total_transactions   → number of purchase records
--   - unique_customers     → number of distinct shoppers

SELECT
    SUM(purchase_amount_usd)        AS total_revenue,        -- total value of all purchases
    COUNT(*)                        AS total_transactions,   -- number of rows / purchases
    COUNT(DISTINCT customer_id)     AS unique_customers      -- distinct customers in the dataset
FROM sales;

-- KPI BLOCK 2: AVERAGE BASKET VALUE (ABV)
-- Objective: measure the average amount spent per transaction.

SELECT
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_basket_value
FROM sales;

-- KPI BLOCK 3: PRODUCT CATEGORY PERFORMANCE
-- Objective: identify top revenue-generating categories to support assortment,
-- inventory, and marketing decisions.

SELECT
    category,
    SUM(purchase_amount_usd) AS revenue,     -- total dollars generated by this category
    COUNT(*)                  AS transactions, -- how many purchases involved this category
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_ticket  -- avg spend per purchase in this category
FROM sales
GROUP BY category
ORDER BY revenue DESC;

SELECT
    category,
    SUM(purchase_amount_usd) AS revenue
FROM sales
GROUP BY category
ORDER BY revenue DESC
LIMIT 5;

-- KPI BLOCK 4: CUSTOMER VALUE SEGMENTATION
-- Objective: identify high-value customers by revenue contribution and frequency.

SELECT
    customer_id,
    SUM(purchase_amount_usd) AS total_spent,       -- total money spent by each customer
    COUNT(*)                  AS transactions,     -- number of orders (frequency)
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_ticket -- average order value
FROM sales
GROUP BY customer_id
ORDER BY total_spent DESC 
limit(10);

-- KPI BLOCK 5: GENDER-BASED REVENUE & BEHAVIOR
-- Objective: analyze customer segments by gender to understand differences in
-- spending behavior, frequency, and average order value.

SELECT
    gender,
    COUNT(*) AS transactions,                          -- number of purchases
    SUM(purchase_amount_usd) AS total_revenue,         -- total revenue per gender
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_ticket -- avg spend per purchase
FROM sales
GROUP BY gender
ORDER BY total_revenue DESC;

-- KPI BLOCK 6: LOCATION-BASED PERFORMANCE
-- Objective: analyze how revenue and purchase behavior vary by location.

SELECT
    location,
    COUNT(*) AS transactions,                      -- number of purchases in this location
    SUM(purchase_amount_usd) AS total_revenue,     -- total revenue generated by this location
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_ticket -- average ticket size
FROM sales
GROUP BY location
ORDER BY total_revenue DESC;


-- KPI BLOCK 7: SEASONALITY ANALYSIS
-- Objective: identify demand and revenue patterns across seasons.

SELECT
    season,
    COUNT(*) AS transactions,                       -- number of purchases in this season
    SUM(purchase_amount_usd) AS total_revenue,      -- total dollars generated in this season
    ROUND(AVG(purchase_amount_usd::NUMERIC), 2) AS avg_ticket -- average order value
FROM sales
GROUP BY season
ORDER BY total_revenue DESC;
